config/routes.rb
Rails.application.routes.draw do
  # resources :users
  resources :washes
  resources :blacklists
  resources :charges
  resources :vehicles

  root 'washes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blacklist.rb
class Blacklist < ApplicationRecord
  def license=(value)
    write_attribute(:license, Vehicle.format_license(value))
  end
end

app/controllers/blacklists_controller.rb
class BlacklistsController < ApplicationController
  before_action :set_blacklist, only: [:show, :edit, :update, :destroy]

  # GET /blacklists
  # GET /blacklists.json
  def index
    @blacklists = Blacklist.all
  end

  # GET /blacklists/1
  # GET /blacklists/1.json
  def show
  end

  # GET /blacklists/new
  def new
    @blacklist = Blacklist.new
  end

  # GET /blacklists/1/edit
  def edit
  end

  # POST /blacklists
  # POST /blacklists.json
  def create
    @blacklist = Blacklist.new(blacklist_params)

    respond_to do |format|
      if @blacklist.save
        format.html { redirect_to @blacklist, notice: 'Blacklist was successfully created.' }
        format.json { render :show, status: :created, location: @blacklist }
      else
        format.html { render :new }
        format.json { render json: @blacklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blacklists/1
  # PATCH/PUT /blacklists/1.json
  def update
    respond_to do |format|
      if @blacklist.update(blacklist_params)
        format.html { redirect_to @blacklist, notice: 'Blacklist was successfully updated.' }
        format.json { render :show, status: :ok, location: @blacklist }
      else
        format.html { render :edit }
        format.json { render json: @blacklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blacklists/1
  # DELETE /blacklists/1.json
  def destroy
    @blacklist.destroy
    respond_to do |format|
      format.html { redirect_to blacklists_url, notice: 'Blacklist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blacklist
      @blacklist = Blacklist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blacklist_params
      params.require(:blacklist).permit(:license)
    end
end

app/helpers/blacklists_helper.rb
module BlacklistsHelper
end

app/views/blacklists/_form.html.erb
<%= form_with(model: blacklist, local: true) do |form| %>
  <% if blacklist.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(blacklist.errors.count, "error") %> prohibited this blacklist from being saved:</h2>

      <ul>
      <% blacklist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :license %>
    <%= form.text_field :license, id: :blacklist_license %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blacklists/edit.html.erb
<h1>Editing Blacklist</h1>

<%= render 'form', blacklist: @blacklist %>

<%= link_to 'Show', @blacklist %> |
<%= link_to 'Back', blacklists_path %>

app/views/blacklists/index.html.erb
<h1>Blacklists</h1>

<table>
  <thead>
    <tr>
      <th>License</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blacklists.each do |blacklist| %>
      <tr>
        <td><%= blacklist.license %></td>
        <td><%= link_to 'Show', blacklist %></td>
        <td><%= link_to 'Edit', edit_blacklist_path(blacklist) %></td>
        <td><%= link_to 'Destroy', blacklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blacklist', new_blacklist_path %>

app/views/blacklists/new.html.erb
<h1>New Blacklist</h1>

<%= render 'form', blacklist: @blacklist %>

<%= link_to 'Back', blacklists_path %>

app/views/blacklists/show.html.erb
<p>
  <strong>License:</strong>
  <%= @blacklist.license %>
</p>

<%= link_to 'Edit', edit_blacklist_path(@blacklist) %> |
<%= link_to 'Back', blacklists_path %>