config/routes.rb
Rails.application.routes.draw do
  # resources :users
  resources :washes
  resources :blacklists
  resources :charges
  resources :vehicles

  root 'washes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wash.rb
class Wash < ApplicationRecord
  belongs_to :vehicle
  has_many :charges
  belongs_to :user
  before_save :calculate_total
  before_save :copy_vehicle_attributes
  before_validation :check_blacklist
  before_validation :check_truck_bed

  def bed_is_up=(value)
    @bed_is_up = ['1', 1, true].include? value
  end

  def bed_is_up?
    !!@bed_is_up
  end

  def mud_in_bed=(value)
    @mud_in_bed = ['1', 1, true].include? value
  end

  def mud_in_bed?
    !!@mud_in_bed
  end

  def calculated_total
    self.charges.reduce(0) { |acc, charge| charge.is_credit? ? acc - charge.amount : acc + charge.amount}
  end

  private

  def check_blacklist
    if vehicle && vehicle.blacklisted?
      errors.add :vehicle, "This vehicle has been reported as stolen!"
    end
  end

  def calculate_total
    self.total = calculated_total
  end

  def check_truck_bed
    if vehicle && vehicle.truck? && !bed_is_up?
      errors.add :vehicle, "Truck bed must be up"
    end
  end

  def copy_vehicle_attributes
    if vehicle
      self.license = vehicle.license
      self.vehicle_type = vehicle.vehicle_type
    end
  end

end

app/controllers/washes_controller.rb
class WashesController < ApplicationController
  before_action :set_wash, only: [:show, :edit, :update, :destroy]

  # GET /washes
  # GET /washes.json
  def index
    @washes = @current_user.washes.order(created_at: :desc)
  end

  # GET /washes/1
  # GET /washes/1.json
  def show
    case Wash.where(vehicle_id: @wash.vehicle_id).count
    when 1
      @show_discount = true
    end
  end

  # GET /washes/new
  def new
    @wash = Wash.new(user: @current_user)
    @vehicle = Vehicle.find_by(license: params[:vehicle]) || Vehicle.new
    @wash.vehicle = @vehicle
  end

  # GET /washes/1/edit
  def edit
  end

  # POST /washes
  # POST /washes.json
  def create
    @wash = Wash.new(wash_params)
    @wash.user = @current_user

    if @wash.valid?
      if @wash.vehicle.car?
        @wash.charges << Charge.new(amount: 5.00, description: 'Car wash')
      else
        @wash.charges << Charge.new(amount: 10.00, description: 'Truck wash')
      end

      if @wash.mud_in_bed?
        @wash.charges << Charge.new(amount: 2.00, description: 'Mud cleaning')
      end

      case Wash.where(vehicle_id: @wash.vehicle_id).count
      when 1
        @wash.charges << Charge.new(amount: (@wash.calculated_total / 2), description: 'Return customer (50% off)', is_credit: true)
      end
    end

    respond_to do |format|
      if @wash.save
        format.html { redirect_to @wash, notice: 'Wash was successfully created.' }
        format.json { render :show, status: :created, location: @wash }
      else
        format.html { render :new }
        format.json { render json: @wash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /washes/1
  # PATCH/PUT /washes/1.json
  def update
    respond_to do |format|
      if @wash.update(wash_params)
        format.html { redirect_to @wash, notice: 'Wash was successfully updated.' }
        format.json { render :show, status: :ok, location: @wash }
      else
        format.html { render :edit }
        format.json { render json: @wash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /washes/1
  # DELETE /washes/1.json
  def destroy
    @wash.destroy
    respond_to do |format|
      format.html { redirect_to washes_url, notice: 'Wash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wash
      @wash = Wash.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wash_params
      params.require(:wash).permit(:vehicle_id, :total, :description, :bed_is_up, :mud_in_bed)
    end
end

app/helpers/washes_helper.rb
module WashesHelper
end

app/views/washes/_form.html.erb
<%= form_with(model: wash, local: true, id: 'new-wash-form') do |form| %>
  <% if wash.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(wash.errors.count, "error") %> prohibited this wash from being saved:</h2>

      <ul>
      <% wash.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.select :vehicle_id do %>
      <option>Please select a vehicle</option>
      <%= @current_user.vehicles.each do |vehicle| -%>
        <option
          value="<%= vehicle.id %>"
          data-vehicle-type="<%= vehicle.vehicle_type %>"
          <%= "selected" if vehicle == wash.vehicle %>>
          <%= vehicle.license %> (<%= vehicle.vehicle_type %>)
        </option>
      <%- end -%>
    <%- end -%>

    <%= link_to 'Add new vehicle', new_vehicle_path %>
  </div>

  <fieldset
    class="section-vehicle-type show-truck"
    data-show="<%= wash.vehicle && wash.vehicle.truck? ? 'true' : 'false' %>">

    <div class="field">
      <%= form.label :mud_in_bed do %>
        <%= form.check_box :mud_in_bed, id: :wash_mud_in_bed %> Truck bed has mud
      <% end %>
    </div>

    <div class="field">
      <%= form.label :bed_is_up do %>
        <%= form.check_box :bed_is_up, id: :wash_bed_is_up %> Truck bed is up
      <% end %>
    </div>
  </fieldset>

  <div class="actions">
    <%= form.submit "Wash my vehicle" %>
  </div>
<% end %>

app/views/washes/edit.html.erb
<h1>Editing Wash</h1>

<%= render 'form', wash: @wash %>

<%= link_to 'Show', @wash %> |
<%= link_to 'Back', washes_path %>

app/views/washes/index.html.erb
<h1>Washes</h1>

<table>
  <thead>
    <tr>
      <th>Vehicle</th>
      <th>Total</th>
      <!-- <th>Description</th> -->
      <th>Washed at</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @washes.each do |wash| %>
      <tr>
        <td><%= wash.license %> (<%= wash.vehicle_type %>)</td>
        <td class="money"><%= number_to_currency wash.total %></td>
        <!-- <td><%= wash.description %></td> -->
        <td><%= wash.created_at.strftime("%B %m, %Y at %r (%Z)") %></td>
        <td><%= link_to 'Show', wash %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wash', new_wash_path %>

app/views/washes/new.html.erb
<h1>Car Wash</h1>
<p>Please select or add a new vehicle to wash</p>

<%= render 'form', wash: @wash %>

app/views/washes/show.html.erb
<h1>Thank you!</h1>

<% if @show_discount %>
  <p><em>Wash this vehicle again for a discount of 50%!</em></p>
<% end %>

<p>Here is your transaction reciept:</p>

<label>
  <div class="reciept">
    <h3>
      <strong>Car wash charges:</strong>
    </h3>

    <div class="license">
      License: <%= @wash.license %> (<%= @wash.vehicle_type %>)
    </div>
    
    <ul>
      <% @wash.charges.each do |charge| %>
        <li>
          <span class="reciept-item"><%= charge.description %></span>
          <span class="reciept-value <%= charge.is_credit? ? 'credit' : 'debit' %>">
            <%= charge.is_credit ? '-' : '' %>
            <%= number_to_currency charge.amount %>
          </span>
        </li>
      <% end %>
    </ul>

    <div class="total">
      <strong>Total:</strong>
      <%= number_to_currency @wash.total %>
    </div>
  </div>
</label>

<nav class="nav-actions">
  <%= link_to 'Edit', edit_wash_path(@wash) %>
  <%= link_to 'Print', 'javascript:window.print()' %>
  <%= link_to 'Wash again!', new_wash_path(vehicle: @wash.license) %>
  <%= link_to 'Wash another vehicle', new_wash_path %>
</nav>