config/routes.rb
Rails.application.routes.draw do
  # resources :users
  resources :washes
  resources :blacklists
  resources :charges
  resources :vehicles

  root 'washes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  enum vehicle_type: %i[car truck]
  has_many :washes
  has_many :ownerships, dependent: :destroy
  has_many :users, through: :ownerships
  validates :license, presence: true, uniqueness: true, format: { with: /[A-Z\d]+/ }, length: { in: 1..8 }

  def license=(value)
    write_attribute(:license, Vehicle.format_license(value))
  end

  def blacklisted?
    Blacklist.where(license: license).any?
  end

  def self.format_license(value)
    value.upcase.gsub(/[^A-Z\d]*/, '')
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = @current_user.vehicles
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.find_or_initialize_by(license: Vehicle.format_license(vehicle_params[:license]))
    @vehicle.update_attributes(vehicle_params)
    add_user
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    add_user
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:name, :vehicle_type, :license)
    end

    def add_user
      @vehicle.users << @current_user unless @vehicle.users.include?(@current_user)
    end

end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vehicle_type %>
    <%= form.select :vehicle_type, Vehicle.vehicle_types.keys %>
  </div>

  <div class="field">
    <%= form.label :license %>
    <%= form.text_field :license, id: :vehicle_license %>
  </div>

  <%- unless hide_actions ||= false -%>
    <div class="actions">
      <%= form.submit %>
    </div>
  <%- end -%>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>License</th>
      <th>Vehicle type</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.license %></td>
        <td><%= vehicle.vehicle_type %></td>
        <td><%= link_to 'Wash', new_wash_path(vehicle: vehicle.license) %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>New Vehicle: </h1>
<%= render 'form', vehicle: @vehicle %>

<!-- <%= link_to 'New Vehicle', new_vehicle_path %> -->

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p>
  <strong>Vehicle type:</strong>
  <%= @vehicle.vehicle_type %>
</p>

<p>
  <strong>License:</strong>
  <%= @vehicle.license %>
</p>

<nav class="nav-actions">
  <%= link_to 'Edit', edit_vehicle_path(@vehicle) %>
  <%= link_to 'My Vehicles', vehicles_path %>
  <%= link_to 'Wash this vehicle', new_wash_path(vehicle: @vehicle.license) %>
</nav>