config/routes.rb
Rails.application.routes.draw do
  # resources :users
  resources :washes
  resources :blacklists
  resources :charges
  resources :vehicles

  root 'washes#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :wash
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]

  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:description, :amount, :wash_id)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= form_with(model: charge, local: true) do |form| %>
  <% if charge.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% charge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :charge_description %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :charge_amount %>
  </div>

  <div class="field">
    <%= form.label :wash_id %>
    <%= form.text_field :wash_id, id: :charge_wash_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<h1>Charges</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Amount</th>
      <th>Credit</th>
      <th>Wash</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charges.each do |charge| %>
      <tr class="<%= charge.is_credit ? 'credit' : 'debit' %>">
        <td><%= charge.description %></td>
        <td><%= charge.is_credit ? '-' : '+' %> <%= number_to_currency charge.amount %></td>
        <td><%= charge.is_credit %></td>
        <td><%= link_to "Wash: #{charge.wash_id}", charge.wash %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @charge.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @charge.amount %>
</p>

<p>
  <strong>Is Credit:</strong>
  <%= @charge.is_credit %>
</p>

<p>
  <strong>Wash:</strong>
  <%= link_to "Wash ID: #{@charge.wash_id}", @charge.wash %>
</p>

<nav class="nav-actions">
  <%= link_to 'Edit', edit_charge_path(@charge) %>
  <%= link_to 'Back', charges_path %>
</nav>